### ISSUE TITLE
Postconditions not applied to predicate.

### ISSUE THREAD

**Issue by rmoehn** [arrdem/guten-tag#4]
The README says that ‘postconditions in the attrs map will be applied […] to the generated predicate’. As far as I see in the code, this is not the case and I don't know what postconditions would make sense for these predicates. However, your statement sounds quite bold, so I wonder what you were thinking when you wrote it.

**Comment by arrdem** [comment]
Hum... this is I think up for debate. In keeping with the smart constructor model, preconditions are highly meaningful because they allow you to express constraints on the properties or domain of inputs. Because constructors are (at present) an identity operation on the input data there is no possible postcondition which must not also have been a precondition. Thus the `:post` guards need not be applied to the predicate.

A more general case of guten-tag could allow for the constructor to compute additional values, somewhat akin to what lib-grimoire does to set the `:grimoire.things/url` cache value. Then having both pre and post conditions would make more sense.

**Comment by rmoehn** [comment]
»There is no possible postcondition which must not also have been a precondition« – Logically yes, but it also needs to be applied. If someone likes postconditions better and attaches those, they would expect them to be checked in the predicate, but they aren't. For example, I considered checking the constructed ATaggedVal as a whole with Prismatic Schema in `:post` instead of checking the individual fields in `:pre`. The predicate would not perform this check.

**Comment by arrdem** [comment]
Fair enough. Will fix.

**Comment by arrdem** [comment]
I suppose I am presuming that pre/post conditions are not generated by a monkey here

**Comment by arrdem** [comment]
Fixed in 0.1.3

**Comment by rmoehn** [comment]
By a monkey? What do you mean?

**Comment by rmoehn** [comment]
Your commit doesn't really fix it, since for the postconditions you have the percent sign syntax, for example, `(odd? %)`. Not that I consider postconditions particularly important. I was more concerned that the code doesn't fulfil the documentation's promises. You could just as well remove that statement…

**Comment by arrdem** [comment]
FEK. Yeah that was a half thought out fix. Lets go with dropping postconditions...

**Comment by arrdem** [comment]
Okay. Fixed for real now. Removed the note about postconditions from the README, explicitly dissoc postconditions in the macro and emit a warning when postconditions are present.

**Comment by rmoehn** [comment]
So ruthless.

**Comment by arrdem** [comment]
![3dc9747c-c0c0-4e98-b696-b05c5585960c](https://cloud.githubusercontent.com/assets/704767/8510427/5a95a88a-2297-11e5-8f52-f958a4b942ac.jpg)
