### ISSUE TITLE
`read-tagged-val` is unsafer than unsafe

### ISSUE THREAD

**Issue by rmoehn** [arrdem/guten-tag#5]
Dealing with the Clojure and EDN readers today has left me in complete puzzlement.

When I saw the source code of `read-tagged-val` and the `eval` in it, I – in my ignorance – thought that `clojure.core/read` evaluates everything it reads and that's why we also have to do it in reader functions. So I prepared a pull request that separated `read-tagged-val` into two flavours, with and without evaluation (for `clojure.edn/read`). However, now I see that `clojure.core/read` only evaluates forms prefixed with `#=` and that only when `*read-eval*` isn't falsey. `read-tagged-val`, as far as I understand it, circumvents this completely and evaluates everything that comes in. Seems rather unsafe to me. Is there a reason for that?

**Comment by rmoehn** [comment]
:see_no_evil:

**Comment by arrdem** [comment]
Oh right this. So this is something I personally do because IMO the `#foo/bar ..` is a reader literal in par with `#{}` and `[]` in that subexpressions should be evaluated. I started doing this for a math with units library where I was writing `#a/b [ <arith expr> <units expr> ]` all the time and didn't want to use constructors.

I consider it a feature, but open to pursuasion. Especially arguments that nested seqs being evaluated as function calls is problematic.

**Comment by rmoehn** [comment]
What do you mean with "subexpressions should be evaluated"?

``` clojure
user=> (ns a.namespace
  #_=>   (:require [guten-tag.core]))
nil
a.namespace=> (ns another.namespace)
nil
another.namespace=> (read-string "[(+ 1 4)]")
[(+ 1 4)]
another.namespace=> (read-string "#g/t [:a/tag {:a-key (+ 1 4)}]")
#g/t [:a/tag {:a-key 5}]
another.namespace=>
```

I'd say this is quite dangerous. If you want the evaluating behaviour, it should be separated and documented as unsafe. And it should not be the default global data reader for guten-tag tagged literals. Before I got confused and posted this issue, I had already made such changes. I think I will revise them and send a PR some time.

**Comment by arrdem** [comment]
Hum. Yeah I'd take a patch for this. Working on ox related fun things right now and not in the mood to fix my shit after fixing Bronsa's all day

**Comment by rmoehn** [comment]
Er, my demo is a bit weird. What I wanted to show is that if any namespace you transitively depend on requires `guten-tag.core`, you will have a data reader that evaluates arbitrary code. If people then follow @michalmarczyk's [clever suggestions on StackOverflow](http://stackoverflow.com/a/16994500/5091738), :bomb:.

I can't take care of StackOverflow, but I'll take care of this issue at least.

**Comment by michalmarczyk** [comment]
Actually `clojure.edn` uses `*default-data-readers*`, but not `*data-readers*`, and it is the latter that is populated from `data_readers.clj` files on the classpath.

So, this prints `:foo`:

``` clj
(read-string "#g/t [:foo {:_ (println :foo)}]")
```

while this does not (and additionally it complains that there is "No reader function for tag g/t"):

``` clj
(clojure.edn/read-string "#g/t [:foo {:_ (println :foo)}]")
```

As for the Stack Overflow answer, I merely explained the documented way to use tagged literals with `clojure.edn`.

**Comment by rmoehn** [comment]
@michalmarczyk: I know about those mechanisms. And on StackOverflow you suggest `(edn/read-string {:readers *data-readers*} "...")`, which is not documented anywhere. – Supposedly for reasons I detailed in the private message you didn't react to. – You're illustrating how to pass custom reader functions to `edn/read-string`. This is perfectly fine. But why do you insist on an example that is potentially dangerous?

**Comment by michalmarczyk** [comment]
The Stack Overflow question specifically asks how to use `*data-readers*` with `clojure.edn`. Since `*data-readers*` holds and is documented to hold a regular map of tag → reader, and since `clojure.edn/{read,read-string}` are documented to accept such maps, the option to pass the former to the latter can hardly be described as undocumented.

You seem to suggest that I should have refused to demonstrate how to do that, however doing so would not have improved anybody's security; indeed, increased awareness of what functionality is available tends to lead to increased ability to assess risk.

I think a mention of the implicit loading of `data_readers.clj` into `*data-readers*` is worth adding, however, in the interests of spreading knowledge about implicit behaviour that could result in surprises. With that addition in place, the answer should contain (at least pointers to) all the information that people may need when making their own informed decisions as to how to use their own edn readers.

As for the private message you mentioned above – sorry about that, Gmail miscategorized your email; I have just read it for the first time.

**Comment by rmoehn** [comment]
(By the way, sorry for hijacking this issue for a discussion about a StackOverflow answer.)

I didn't suggest that you should have refused to demonstrate that. Sorry for not expressing myself clearly enough. But I wouldn't trust peoples' informed decisions too much. My informed decision before I saw and found out a few things would have been: »Oh, cool, then I'll just pass `*data-readers*`.« Maybe mentioning the implicit loading would be enough. I think if it's written explicitly enough and if people would read it, most of them would understand and be careful. However, people don't like reading prose. I'm afraid that the average programmer's eyes anchor at the bottom of the code box and see that stunningly easy solution.

That's why I'd suggest something like this:

``` clojure
(edn/read-string {:readers (select-keys *data-readers*
                                        #{'safe.literal/see-text-above})}
                 "...")
```

I kind of wrote that in my email, but in a bit of a garbled fashion, I guess.

**Comment by michalmarczyk** [comment]
Just added a new section to the answer.

**Comment by rmoehn** [comment]
Alright, thanks!

(And thanks, Reid, for your patience.)

**Comment by michalmarczyk** [comment]
Indeed, sorry for the thread hijack.
